version: '3.8'
services:

  server:
    image: 'server-flwr:latest'
    logging:
      driver: local
    container_name: fl_server
    environment:
      - SERVER_IP=0.0.0.0:9999
      - NUM_CLIENTS=20
      - NUM_ROUNDS=15
      - DATASET=MNIST
      - STRATEGY=CIA
      - PERC_OF_CLIENTS=0.5
      - DECAY=0.05
      - ENGAGED_CLIENTS=7,4,19,9,13,12,15,3
      - SELECT_CLIENT_METHOD=deev
      - EXPLOITATION=0.8
      - EXPLORATION=0.2
      - LEAST_SELECT_FACTOR=0.5
    volumes:
      - ./logs-deev:/logs-deev:rw
      - ./server/strategies_manager.py:/app/strategies_manager.py:r
      - ./server/strategies:/app/strategies/:r
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
    

  client-0:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=0
      - NUM_CLIENTS=20
      - DATASET=MNIST
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=False
      - DIRICHLET_ALPHA=0.1
      - SELECT_CLIENT_METHOD=deev
    volumes:
      - ./logs-deev:/logs-deev:rw
      - ./client/strategies_manager.py:/client/strategies_manager.py:r
      - ./client/strategies:/client/strategies/:r
      - ./client/strategies/engagement_strategy:/client/strategies/engagement_strategy/
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-1:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=1
      - NUM_CLIENTS=20
      - DATASET=MNIST
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=False
      - DIRICHLET_ALPHA=0.1
      - SELECT_CLIENT_METHOD=deev
    volumes:
      - ./logs-deev:/logs-deev:rw
      - ./client/strategies_manager.py:/client/strategies_manager.py:r
      - ./client/strategies:/client/strategies/:r
      - ./client/strategies/engagement_strategy:/client/strategies/engagement_strategy/
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-2:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=2
      - NUM_CLIENTS=20
      - DATASET=MNIST
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=False
      - DIRICHLET_ALPHA=0.1
      - SELECT_CLIENT_METHOD=deev
    volumes:
      - ./logs-deev:/logs-deev:rw
      - ./client/strategies_manager.py:/client/strategies_manager.py:r
      - ./client/strategies:/client/strategies/:r
      - ./client/strategies/engagement_strategy:/client/strategies/engagement_strategy/
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-3:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=3
      - NUM_CLIENTS=20
      - DATASET=MNIST
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=True
      - DIRICHLET_ALPHA=0.1
      - SELECT_CLIENT_METHOD=deev
    volumes:
      - ./logs-deev:/logs-deev:rw
      - ./client/strategies_manager.py:/client/strategies_manager.py:r
      - ./client/strategies:/client/strategies/:r
      - ./client/strategies/engagement_strategy:/client/strategies/engagement_strategy/
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-4:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=4
      - NUM_CLIENTS=20
      - DATASET=MNIST
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=True
      - DIRICHLET_ALPHA=0.1
      - SELECT_CLIENT_METHOD=deev
    volumes:
      - ./logs-deev:/logs-deev:rw
      - ./client/strategies_manager.py:/client/strategies_manager.py:r
      - ./client/strategies:/client/strategies/:r
      - ./client/strategies/engagement_strategy:/client/strategies/engagement_strategy/
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-5:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=5
      - NUM_CLIENTS=20
      - DATASET=MNIST
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=False
      - DIRICHLET_ALPHA=0.1
      - SELECT_CLIENT_METHOD=deev
    volumes:
      - ./logs-deev:/logs-deev:rw
      - ./client/strategies_manager.py:/client/strategies_manager.py:r
      - ./client/strategies:/client/strategies/:r
      - ./client/strategies/engagement_strategy:/client/strategies/engagement_strategy/
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-6:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=6
      - NUM_CLIENTS=20
      - DATASET=MNIST
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=False
      - DIRICHLET_ALPHA=0.1
      - SELECT_CLIENT_METHOD=deev
    volumes:
      - ./logs-deev:/logs-deev:rw
      - ./client/strategies_manager.py:/client/strategies_manager.py:r
      - ./client/strategies:/client/strategies/:r
      - ./client/strategies/engagement_strategy:/client/strategies/engagement_strategy/
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-7:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=7
      - NUM_CLIENTS=20
      - DATASET=MNIST
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=True
      - DIRICHLET_ALPHA=0.1
      - SELECT_CLIENT_METHOD=deev
    volumes:
      - ./logs-deev:/logs-deev:rw
      - ./client/strategies_manager.py:/client/strategies_manager.py:r
      - ./client/strategies:/client/strategies/:r
      - ./client/strategies/engagement_strategy:/client/strategies/engagement_strategy/
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-8:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=8
      - NUM_CLIENTS=20
      - DATASET=MNIST
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=False
      - DIRICHLET_ALPHA=0.1
      - SELECT_CLIENT_METHOD=deev
    volumes:
      - ./logs-deev:/logs-deev:rw
      - ./client/strategies_manager.py:/client/strategies_manager.py:r
      - ./client/strategies:/client/strategies/:r
      - ./client/strategies/engagement_strategy:/client/strategies/engagement_strategy/
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-9:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=9
      - NUM_CLIENTS=20
      - DATASET=MNIST
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=True
      - DIRICHLET_ALPHA=0.1
      - SELECT_CLIENT_METHOD=deev
    volumes:
      - ./logs-deev:/logs-deev:rw
      - ./client/strategies_manager.py:/client/strategies_manager.py:r
      - ./client/strategies:/client/strategies/:r
      - ./client/strategies/engagement_strategy:/client/strategies/engagement_strategy/
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-10:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=10
      - NUM_CLIENTS=20
      - DATASET=MNIST
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=False
      - DIRICHLET_ALPHA=0.1
      - SELECT_CLIENT_METHOD=deev
    volumes:
      - ./logs-deev:/logs-deev:rw
      - ./client/strategies_manager.py:/client/strategies_manager.py:r
      - ./client/strategies:/client/strategies/:r
      - ./client/strategies/engagement_strategy:/client/strategies/engagement_strategy/
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-11:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=11
      - NUM_CLIENTS=20
      - DATASET=MNIST
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=False
      - DIRICHLET_ALPHA=0.1
      - SELECT_CLIENT_METHOD=deev
    volumes:
      - ./logs-deev:/logs-deev:rw
      - ./client/strategies_manager.py:/client/strategies_manager.py:r
      - ./client/strategies:/client/strategies/:r
      - ./client/strategies/engagement_strategy:/client/strategies/engagement_strategy/
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-12:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=12
      - NUM_CLIENTS=20
      - DATASET=MNIST
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=True
      - DIRICHLET_ALPHA=0.1
      - SELECT_CLIENT_METHOD=deev
    volumes:
      - ./logs-deev:/logs-deev:rw
      - ./client/strategies_manager.py:/client/strategies_manager.py:r
      - ./client/strategies:/client/strategies/:r
      - ./client/strategies/engagement_strategy:/client/strategies/engagement_strategy/
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-13:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=13
      - NUM_CLIENTS=20
      - DATASET=MNIST
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=True
      - DIRICHLET_ALPHA=0.1
      - SELECT_CLIENT_METHOD=deev
    volumes:
      - ./logs-deev:/logs-deev:rw
      - ./client/strategies_manager.py:/client/strategies_manager.py:r
      - ./client/strategies:/client/strategies/:r
      - ./client/strategies/engagement_strategy:/client/strategies/engagement_strategy/
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-14:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=14
      - NUM_CLIENTS=20
      - DATASET=MNIST
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=False
      - DIRICHLET_ALPHA=0.1
      - SELECT_CLIENT_METHOD=deev
    volumes:
      - ./logs-deev:/logs-deev:rw
      - ./client/strategies_manager.py:/client/strategies_manager.py:r
      - ./client/strategies:/client/strategies/:r
      - ./client/strategies/engagement_strategy:/client/strategies/engagement_strategy/
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-15:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=15
      - NUM_CLIENTS=20
      - DATASET=MNIST
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=True
      - DIRICHLET_ALPHA=0.1
      - SELECT_CLIENT_METHOD=deev
    volumes:
      - ./logs-deev:/logs-deev:rw
      - ./client/strategies_manager.py:/client/strategies_manager.py:r
      - ./client/strategies:/client/strategies/:r
      - ./client/strategies/engagement_strategy:/client/strategies/engagement_strategy/
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-16:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=16
      - NUM_CLIENTS=20
      - DATASET=MNIST
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=False
      - DIRICHLET_ALPHA=0.1
      - SELECT_CLIENT_METHOD=deev
    volumes:
      - ./logs-deev:/logs-deev:rw
      - ./client/strategies_manager.py:/client/strategies_manager.py:r
      - ./client/strategies:/client/strategies/:r
      - ./client/strategies/engagement_strategy:/client/strategies/engagement_strategy/
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-17:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=17
      - NUM_CLIENTS=20
      - DATASET=MNIST
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=False
      - DIRICHLET_ALPHA=0.1
      - SELECT_CLIENT_METHOD=deev
    volumes:
      - ./logs-deev:/logs-deev:rw
      - ./client/strategies_manager.py:/client/strategies_manager.py:r
      - ./client/strategies:/client/strategies/:r
      - ./client/strategies/engagement_strategy:/client/strategies/engagement_strategy/
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-18:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=18
      - NUM_CLIENTS=20
      - DATASET=MNIST
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=False
      - DIRICHLET_ALPHA=0.1
      - SELECT_CLIENT_METHOD=deev
    volumes:
      - ./logs-deev:/logs-deev:rw
      - ./client/strategies_manager.py:/client/strategies_manager.py:r
      - ./client/strategies:/client/strategies/:r
      - ./client/strategies/engagement_strategy:/client/strategies/engagement_strategy/
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-19:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=19
      - NUM_CLIENTS=20
      - DATASET=MNIST
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=True
      - DIRICHLET_ALPHA=0.1
      - SELECT_CLIENT_METHOD=deev
    volumes:
      - ./logs-deev:/logs-deev:rw
      - ./client/strategies_manager.py:/client/strategies_manager.py:r
      - ./client/strategies:/client/strategies/:r
      - ./client/strategies/engagement_strategy:/client/strategies/engagement_strategy/
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

