version: '3.8'
services:

  server:
    image: 'server-flwr:latest'
    logging:
      driver: local
    container_name: fl_server
    environment:
      - SERVER_IP=0.0.0.0:9999
      - NUM_CLIENTS=10
      - NUM_ROUNDS=10
      - DATASET=mnist
    volumes:
      - ./logs:/logs:rw
      - ./server/strategies_manager.py:/app/strategies_manager.py:r
      - ./server/strategies:/app/strategies/:r
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
    

  client-0:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=0
      - NUM_CLIENTS=10
      - DATASET=mnist
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=True
    volumes:
      - ./logs:/logs
      - ./client/strategies_manager.py:/app/strategies_manager.py:r
      - ./client/strategies/client.py:/app/strategies/client.py
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-1:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=1
      - NUM_CLIENTS=10
      - DATASET=mnist
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=False
    volumes:
      - ./logs:/logs
      - ./client/strategies_manager.py:/app/strategies_manager.py:r
      - ./client/strategies/client.py:/app/strategies/client.py
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-2:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=2
      - NUM_CLIENTS=10
      - DATASET=mnist
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=False
    volumes:
      - ./logs:/logs
      - ./client/strategies_manager.py:/app/strategies_manager.py:r
      - ./client/strategies/client.py:/app/strategies/client.py
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-3:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=3
      - NUM_CLIENTS=10
      - DATASET=mnist
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=False
    volumes:
      - ./logs:/logs
      - ./client/strategies_manager.py:/app/strategies_manager.py:r
      - ./client/strategies/client.py:/app/strategies/client.py
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-4:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=4
      - NUM_CLIENTS=10
      - DATASET=mnist
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=True
    volumes:
      - ./logs:/logs
      - ./client/strategies_manager.py:/app/strategies_manager.py:r
      - ./client/strategies/client.py:/app/strategies/client.py
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-5:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=5
      - NUM_CLIENTS=10
      - DATASET=mnist
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=True
    volumes:
      - ./logs:/logs
      - ./client/strategies_manager.py:/app/strategies_manager.py:r
      - ./client/strategies/client.py:/app/strategies/client.py
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-6:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=6
      - NUM_CLIENTS=10
      - DATASET=mnist
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=False
    volumes:
      - ./logs:/logs
      - ./client/strategies_manager.py:/app/strategies_manager.py:r
      - ./client/strategies/client.py:/app/strategies/client.py
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-7:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=7
      - NUM_CLIENTS=10
      - DATASET=mnist
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=False
    volumes:
      - ./logs:/logs
      - ./client/strategies_manager.py:/app/strategies_manager.py:r
      - ./client/strategies/client.py:/app/strategies/client.py
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-8:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=8
      - NUM_CLIENTS=10
      - DATASET=mnist
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=False
    volumes:
      - ./logs:/logs
      - ./client/strategies_manager.py:/app/strategies_manager.py:r
      - ./client/strategies/client.py:/app/strategies/client.py
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-9:
    image: 'client-flwr:latest'
    logging:
      driver: local
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=9
      - NUM_CLIENTS=10
      - DATASET=mnist
      - STRATEGY=CIA
      - LOCAL_EPOCHS=1
      - NO_IDD=True
      - PARTICIPATE=False
    volumes:
      - ./logs:/logs
      - ./client/strategies_manager.py:/app/strategies_manager.py:r
      - ./client/strategies/client.py:/app/strategies/client.py
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

